epsilons=$1
python main_yyf.py --attack_name L2ContrastReductionAttack --epsilons $epsilons  
python main_yyf.py --attack_name VirtualAdversarialAttack --epsilons $epsilons  
python main_yyf.py --attack_name DDNAttack --epsilons $epsilons  
python main_yyf.py --attack_name L2ProjectedGradientDescentAttack --epsilons $epsilons  
python main_yyf.py --attack_name LinfProjectedGradientDescentAttack --epsilons $epsilons  
python main_yyf.py --attack_name LinfBasicIterativeAttack --epsilons $epsilons  
python main_yyf.py --attack_name L2FastGradientAttack --epsilons $epsilons  
python main_yyf.py --attack_name LinfFastGradientAttack --epsilons $epsilons  
python main_yyf.py --attack_name L2AdditiveGaussianNoiseAttack --epsilons $epsilons  
python main_yyf.py --attack_name L2AdditiveUniformNoiseAttack --epsilons $epsilons   
python main_yyf.py --attack_name L2ClippingAwareAdditiveGaussianNoiseAttack --epsilons $epsilons  
python main_yyf.py --attack_name L2ClippingAwareAdditiveUniformNoiseAttack --epsilons $epsilons  
python main_yyf.py --attack_name LinfAdditiveUniformNoiseAttack --epsilons $epsilons  
python main_yyf.py --attack_name L2RepeatedAdditiveGaussianNoiseAttack --epsilons $epsilons  
python main_yyf.py --attack_name L2RepeatedAdditiveUniformNoiseAttack --epsilons $epsilons  
python main_yyf.py --attack_name L2ClippingAwareRepeatedAdditiveGaussianNoiseAttack --epsilons $epsilons  
python main_yyf.py --attack_name L2ClippingAwareRepeatedAdditiveUniformNoiseAttack --epsilons $epsilons  
python main_yyf.py --attack_name LinfRepeatedAdditiveUniformNoiseAttack --epsilons $epsilons  
python main_yyf.py --attack_name InversionAttack --epsilons $epsilons  
python main_yyf.py --attack_name BinarySearchContrastReductionAttack --epsilons $epsilons  
python main_yyf.py --attack_name LinearSearchContrastReductionAttack --epsilons $epsilons  
#python main_yyf.py --attack_name L2CarliniWagnerAttack --epsilons $epsilons  
python main_yyf.py --attack_name NewtonFoolAttack --epsilons $epsilons  
python main_yyf.py --attack_name EADAttack --epsilons $epsilons  
python main_yyf.py --attack_name GaussianBlurAttack --epsilons $epsilons  
python main_yyf.py --attack_name L2DeepFoolAttack --epsilons $epsilons  
python main_yyf.py --attack_name LinfDeepFoolAttack --epsilons $epsilons  
python main_yyf.py --attack_name SaltAndPepperNoiseAttack --epsilons $epsilons  
python main_yyf.py --attack_name LinearSearchBlendedUniformNoiseAttack --epsilons $epsilons  
python main_yyf.py --attack_name BinarizationRefinementAttack --epsilons $epsilons  
python main_yyf.py --attack_name DatasetAttack --epsilons $epsilons  
python main_yyf.py --attack_name BoundaryAttack --epsilons $epsilons  
python main_yyf.py --attack_name L0BrendelBethgeAttack --epsilons $epsilons  
python main_yyf.py --attack_name L1BrendelBethgeAttack --epsilons $epsilons  
python main_yyf.py --attack_name L2BrendelBethgeAttack --epsilons $epsilons  
python main_yyf.py --attack_name L0FMNAttack --epsilons $epsilons  
python main_yyf.py --attack_name L1FMNAttack --epsilons $epsilons  
python main_yyf.py --attack_name L2FMNAttack --epsilons $epsilons  
python main_yyf.py --attack_name LInfFMNAttack --epsilons $epsilons  
python main_yyf.py --attack_name PointwiseAttack --epsilons $epsilons  
python main_yyf.py --attack_name FGM --epsilons $epsilons  
python main_yyf.py --attack_name FGSM --epsilons $epsilons  
python main_yyf.py --attack_name L2PGD --epsilons $epsilons  
python main_yyf.py --attack_name LinfPGD --epsilons $epsilons  
python main_yyf.py --attack_name PGD --epsilons $epsilons  