python main_yyf.py --attack_name L2ProjectedGradientDescentAttack --epsilons 4.0
python main_yyf.py --attack_name L2ProjectedGradientDescentAttack --epsilons 3.2
python main_yyf.py --attack_name L2ProjectedGradientDescentAttack --epsilons 3.3
python main_yyf.py --attack_name L2ProjectedGradientDescentAttack --epsilons 3.4
python main_yyf.py --attack_name L2ProjectedGradientDescentAttack --epsilons 3.5
python main_yyf.py --attack_name L2ProjectedGradientDescentAttack --epsilons 3.6
python main_yyf.py --attack_name L2ProjectedGradientDescentAttack --epsilons 3.7
python main_yyf.py --attack_name L2ProjectedGradientDescentAttack --epsilons 3.8
python main_yyf.py --attack_name L2ProjectedGradientDescentAttack --epsilons 3.9
python main_yyf.py --attack_name L2ProjectedGradientDescentAttack --epsilons 4.1
python main_yyf.py --attack_name L2ProjectedGradientDescentAttack --epsilons 4.2
python main_yyf.py --attack_name L2ProjectedGradientDescentAttack --epsilons 4.3
python main_yyf.py --attack_name L2ProjectedGradientDescentAttack --epsilons 4.4
python main_yyf.py --attack_name L2ProjectedGradientDescentAttack --epsilons 4.5
python main_yyf.py --attack_name L2ProjectedGradientDescentAttack --epsilons 4.6
python main_yyf.py --attack_name L2ProjectedGradientDescentAttack --epsilons 4.7
python main_yyf.py --attack_name L2ProjectedGradientDescentAttack --epsilons 4.8
python main_yyf.py --attack_name L2ProjectedGradientDescentAttack --epsilons 4.9